sprites.onOverlap(SpriteKind.Player, SpriteKind.Player, function (sprite, otherSprite) {
    info.startCountdown(7)
})
function showInstruction (text: string) {
    game.splash("Welcome To Kenny's Game")
    game.showLongText("Before we get started here are some instructions!", DialogLayout.Bottom)
    game.showLongText("Use the arrow keys to move", DialogLayout.Bottom)
    game.showLongText("To win the game, complete the maze by finding the two open chests!", DialogLayout.Bottom)
    game.showLongText("You are on a time limit of 7 seconds", DialogLayout.Bottom)
    game.showLongText("However, every time you hover over a closed chest, your time restarts!", DialogLayout.Bottom)
    game.showLongText("Once that clock hits zero, you lose!!!", DialogLayout.Bottom)
    game.showLongText("Good luck and see you at the opened chest... hopefully", DialogLayout.Bottom)
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestOpen, function (sprite, location) {
    game.over(true, effects.confetti)
})
let mySprite2: Sprite = null
tiles.setCurrentTilemap(tilemap`level3`)
let mySprite = sprites.create(img`
    ........................
    ........................
    ......22................
    .....2222...............
    ....eeeeee..............
    ...e222222ee............
    ..e2ffffff2e............
    ..fffeeeefff............
    ..efbf44fbfe............
    .ee41fddf14ee...........
    .ffffdddddee............
    .ddddf444ee.............
    .bbbbf2222f4e...........
    .bbbbf2222fd4...........
    ..ccf45544f44...........
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
scene.cameraFollowSprite(mySprite)
mySprite.setPosition(12, 90)
for (let value of tiles.getTilesByType(sprites.dungeon.chestClosed)) {
    mySprite2 = sprites.create(img`
        . . b b b b b b b b b b b b . . 
        . b e 4 4 4 4 4 4 4 4 4 4 e b . 
        b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
        b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
        b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
        b e e 4 4 4 4 4 4 4 4 4 4 e e b 
        b e e e e e e e e e e e e e e b 
        b e e e e e e e e e e e e e e b 
        b b b b b b b d d b b b b b b b 
        c b b b b b b c c b b b b b b c 
        c c c c c c b c c b c c c c c c 
        b e e e e e c b b c e e e e e b 
        b e e e e e e e e e e e e e e b 
        b c e e e e e e e e e e e e c b 
        b b b b b b b b b b b b b b b b 
        . b b . . . . . . . . . . b b . 
        `, SpriteKind.Player)
    tiles.placeOnTile(mySprite2, value)
}
showInstruction("abc")
forever(function () {
    music.playMelody("C5 B A G F E D C ", 120)
})
